apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sentiment-ingress
  namespace: app
spec:
  rules:
    - host: sentiment.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: sentiment-app
                port:
                  number: 80
