apiVersion: v1
kind: Service
metadata:
  name: sentiment-app
  namespace: app
  labels:
    app: sentiment-app        # ← ВАЖНО: совпадает с ServiceMonitor.spec.selector.matchLabels
spec:
  type: LoadBalancer
  selector:
    app: sentiment-app        # это как раньше: матчит Pod’ы
  ports:
    - name: http              # ← имя порта, по нему смотрит ServiceMonitor.endpoints.port
      port: 80
      targetPort: 8080